export async function fetchNotes(){}
export async function fetchNoteById(){}
export async function createNote(){}
export async function deleteNote(){}
export async function login(){}
export async function logout(){}
export async function checkSession(){}
export async function getMe(){}
export async function updateMe(){}